{% set name = "PyTrack" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cosbidev/PyTrack/archive/v{{ version }}.tar.gz
  sha256: dd11b87a946e005f36ae7f17c0efc31191835942fc8c5f8153bc07e7671c7961

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - folium >=0.12.1.post1,==0.12.1.*
    - matplotlib-base >=3.5.2,==3.5.*
    - networkx >=2.8.2,==2.8.*
    - numpy >=1.22.3,==1.22.*
    - pandas >=1.4.2,==1.4.*
    - pydot >=1.2.4,==1.2.*
    - pyproj >=3.3.1,==3.3.*
    - python >=3.7
    - python-graphviz
    - requests >=2.28.1,==2.28.*
    - scikit-learn >=1.1.1,==1.1.*
    - setuptools >=63.1.0,==63.1.*
    - shapely >=1.8.2,==1.8.*

test:
  imports:
    - pytrack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cosbidev/PyTrack
  summary: a Map-Matching-based Python Toolbox for Vehicle Trajectory Reconstruction
  description: |
    PyTrack is a Python package that integrate the recorded GPS coordinates with data provided by the open-source OpenStreetMap (OSM). 
    PyTrack can serve the intelligent transport research, e.g. to develop virtual simulation environments for the first training phase 
    in self-driving vehicle applications, to reconstruct the video of a vehicle’s route by exploiting available data and without equipping 
    it with camera sensors, to update the urban road network, and so on.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mtortora-ai
