{% set name = "PyTrack" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cosbidev/PyTrack/archive/v{{ version }}.tar.gz
  sha256: 78a6cfd5b5d4f58a20bf4b305414a5bf760600873de4a389a2df98b7d28c43a2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - folium
    - networkx
    - shapely
    - pandas
    - numpy
    - requests
    - pyproj
    - scikit-learn
    - matplotlib-base
    - setuptools
    - pydot
    - python-graphviz

test:
  imports:
    - pytrack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cosbidev/PyTrack
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mtortora-ai
