{% set name = "PyTrack" %}
{% set version = "2.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cosbidev/PyTrack/archive/v{{ version }}.tar.gz
  sha256: bccfa33858003f8ae79e837b26f50d0e29d22530c170827ffb891b03be778850

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - folium >=0.13.0,==0.13.*
    - networkx >=2.8.6,==2.8.*
    - shapely >=1.8.4,==1.8.*
    - pandas >=1.4.4,==1.4.*
    - numpy >=1.23.2,==1.23.*
    - requests >=2.28.1,==2.28.*
    - pyproj >=3.3.1,==3.3.*
    - scikit-learn >=1.1.2,==1.1.*
    - matplotlib-base >=3.5.3,==3.5.*
    - setuptools >=65.3.0,==65.3.*
    - pydot >=1.4.2,==1.4.*
    - python-graphviz >=0.20.1,==0.20.*

test:
  imports:
    - pytrack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cosbidev/PyTrack
  summary: a Map-Matching-based Python Toolbox for Vehicle Trajectory Reconstruction
  description: |
      PyTrack is a Python package that integrate the recorded GPS coordinates with data provided by the open-source OpenStreetMap (OSM). 
      PyTrack can serve the intelligent transport research, e.g. to develop virtual simulation environments for the first training phase 
      in self-driving vehicle applications, to reconstruct the video of a vehicle’s route by exploiting available data and without equipping 
      it with camera sensors, to update the urban road network, and so on.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mtortora-ai
